### ISSUE TITLE
Access Forbidden when moving task between columns - v1.2.20

### ISSUE THREAD

**Issue by billy-syrett** [kanboard/kanboard#4834]
Since upgrading to v1.2.20, moving a task between columns results in the error message `Access Forbidden`.

All other functions that I've tested work fine, all tasks display properly, I can edit the tasks and the projects, just not move the tasks between columns.

Downgrading to v1.2.19 resolves the issue.

**Comment by manne65-hd** [comment]
You might have to provide some more information about your installation ... and maybe installed plugins!

On my local testboard I cannot replicate this error!

- Application version: 1.2.20
- PHP version: 7.3.11
- PHP SAPI: apache2handler
- HTTP Client: cURL
- OS version: Windows NT 10.0
- Database driver: mysql
- Database version: 10.4.8-MariaDB

**Comment by ComodoGAR** [comment]
I have the same problem. Running as a Docker container:

    Version: v1.2.20
    PHP version: 7.4.19
    PHP SAPI: fpm-fcgi
    HTTP client: cURL
    OS Version: Linux 5.4.0-72-generic
    Database driver: sqlite
    Database version: 3.34.1
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

**Comment by billy-syrett** [comment]
Please see installation details below, mine's also running as a Docker container.

```
Application version: v1.2.20
PHP version: 7.4.19
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 5.10.28-Unraid
Database driver: sqlite
Database version: 3.34.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
```

I have 2 plugins installed:
- [HighlightCodeSyntax](https://github.com/kenlog/HighlightCodeSyntax)
- [Greenwing](https://github.com/Confexion/Greenwing)

It's this POST request that is failing with a 403 status code:
`https://projects.DEDACTED.com/?controller=BoardAjaxController&action=save&project_id=1`

CURL:
```
curl 'https://projects.REDACTED.com/?controller=BoardAjaxController&action=save&project_id=1' \
  -H 'authority: projects.DEDACTED.com' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'accept: */*' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'origin: https://projects.REDACTED.com' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8,la;q=0.7' \
  -H 'cookie: DEDACTED' \
  --data-raw '{"task_id":"68","src_column_id":"5","dst_column_id":"4","swimlane_id":"1","position":2}' \
  --compressed
```

**Comment by wucherpfennig** [comment]
I can second that issue. Moving tasks no longer possible. After removing `Greenwing` issues are gone...

**Comment by coffeverton** [comment]
Had the same issue. In my case, the culprit was the Backlog plugin - https://github.com/vistree/kanboard-backlog

**Comment by dharakos** [comment]
I'm running backlog too - So I guess that's the issue for me....

**Comment by kwetnico** [comment]
I have same problem and i don't have Baclog plugin : 

Version de l'application : 1.2.20
Version de PHP : 7.4.19
PHP SAPI : apache2handler
Client HTTP : socket
Version du système d'exploitation : Windows NT 6.3
Type de base de données : mysql
Version de la base de donnée : 5.7.30-log
Navigateur web : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Comment by coffeverton** [comment]
@kwetnico you may need to check for other plugins that may be causing the issue. Disable them all, and enable one by one until the error returns.

After you move the task, the front-end makes an ajax request to the back-end. This request must include an csrf token. I found that the Backlog plugin does not include this token, so the back-end refuses to accept the request.

**Comment by kwetnico** [comment]
The problem is that it does it randomly

> @kwetnico you may need to check for other plugins that may be causing the issue. Disable them all, and enable one by one until the error returns.
> 
> After you move the task, the front-end makes an ajax request to the back-end. This request must include an csrf token. I found that the Backlog plugin does not include this token, so the back-end refuses to accept the request.

The problem is that it does it randomly

**Comment by thatguy-za** [comment]
I have had this issue when I run the docker image of Kanboard v1.2.20 with [Greenwing](https://github.com/Confexion/Greenwing). The problem goes away if I downgrade to the docker image of Kanboard v1.2.19 and keep the same Greenwing config.

There seem to be a couple reports of this issue on the Greenwing github repo - [report 1](https://github.com/Confexion/Greenwing/issues/51), [report 2 (closed - duplicate)](https://github.com/Confexion/Greenwing/issues/47), [report 3 (closed - duplicate)](https://github.com/Confexion/Greenwing/issues/20), [report 4 (closed- duplicate)](https://github.com/Confexion/Greenwing/issues/15).

**Comment by kwetnico** [comment]
> I have had this issue when I run the docker image of Kanboard v1.2.20 with [Greenwing](https://github.com/Confexion/Greenwing). The problem goes away if I downgrade to the docker image of Kanboard v1.2.19 and keep the same Greenwing config.
> 
> There seem to be a couple reports of this issue on the Greenwing github repo - [report 1](https://github.com/Confexion/Greenwing/issues/51), [report 2 (closed - duplicate)](https://github.com/Confexion/Greenwing/issues/47), [report 3 (closed - duplicate)](https://github.com/Confexion/Greenwing/issues/20), [report 4 (closed- duplicate)](https://github.com/Confexion/Greenwing/issues/15).

Thank you I will surely do the same if no solutino is found, I updated all my plugins in Kanboard and it's always the same thing.
I never had this problem except since 1.2.20

**Comment by wucherpfennig** [comment]
> > I have had this issue when I run the docker image of Kanboard v1.2.20 with [Greenwing](https://github.com/Confexion/Greenwing). The problem goes away if I downgrade to the docker image of Kanboard v1.2.19 and keep the same Greenwing config.
> > There seem to be a couple reports of this issue on the Greenwing github repo - [report 1](https://github.com/Confexion/Greenwing/issues/51), [report 2 (closed - duplicate)](https://github.com/Confexion/Greenwing/issues/47), [report 3 (closed - duplicate)](https://github.com/Confexion/Greenwing/issues/20), [report 4 (closed- duplicate)](https://github.com/Confexion/Greenwing/issues/15).
> 
> Thank you I will surely do the same if no solution is found, I updated all my plugins in Kanboard and it's always the same thing.
> I never had this problem except since 1.2.20

We had the same issue (as stated above) and it it has been resolved by updating Greenwing to the latest release. I do not know whether it helps but attached you will find our plugins list:

```
AutoSubtasks  
Coverimage            
Gantt      
Group_assign  
Milestone            
SendEmailCreator  
Calendar      
Creecros_Filter_Pack  
Greenwing  
Kanext        
RandomColorSelector  
Task2pdf
```

**Comment by kwetnico** [comment]
> Greenwing

in my opinion the problem does not come from this plugin ... I do not use Greenwing and I have the problem ...

**Comment by dharakos** [comment]
I don't use it either - Same issue

**Comment by thatguy-za** [comment]
> I don't use it either - Same issue

That's really weird. The issue went away when I removed Greenwing from v1.2.20 but that could be coincidence.

**Comment by dharakos** [comment]
I've seen another thread where people mentioned it went away with disabling
a plugin (Can't remember which - Not greening I don't think) but it was a
plugin I also don't use.

**Comment by ChewingBever** [comment]
I'm also experiencing this issue. I'm running the `latest` Docker tag which, as of writing this, is the `1.2.20` release. The issues started happening after I installed the Greenwing plugin and went away as soon as I removed it, just like with @wucherpfennig. The only other plugin I have installed is UpdateNotifier v1.4.3.

**Comment by katywings** [comment]
I can also confirm this: As soon as I install Greenwing the problem is happening, and when I remove it, the problem goes away :thinking:

**Comment by innc11** [comment]
A temporarily solution is to comment out the code about CSRF check (line 24 in the file app/Controller/BoardAjaxController.php), if you are using Kanboard 1.2.20.

Like this:

```
    public function save()
    {
        // $this->checkReusableGETCSRFParam();
        $project_id = $this->request->getIntegerParam('project_id');

        if (! $project_id || ! $this->request->isAjax()) {
            throw new AccessForbiddenException();
        }
```

**Comment by kwetnico** [comment]
> A temporarily solution is to comment out the code about CSRF check (line 24 in the file app/Controller/BoardAjaxController.php), if you are using Kanboard 1.2.20.
> 
> Like this:
> 
> ```
>     public function save()
>     {
>         // $this->checkReusableGETCSRFParam();
>         $project_id = $this->request->getIntegerParam('project_id');
> 
>         if (! $project_id || ! $this->request->isAjax()) {
>             throw new AccessForbiddenException();
>         }
> ```

Thanks for the tip, the problem is taken into account by the community for a possible debug for the next version? Thank you

**Comment by dharakos** [comment]
Legend - Thanks so much!

**Comment by isAAAc** [comment]
same issue here, a fresh v1.2.20, debian 10.10, sqlite3
tips is working

**Comment by c-o-m-m-a-n-d-e-r-d-a-t-a** [comment]
I also had the issue, no plugins installed at all. Fixed by commenting out line as detailed above by asforest.

Info:
    Application version: 1.2.20
    PHP version: 8.0.8
    PHP SAPI: apache2handler
    HTTP Client: cURL
    OS version: Linux 5.13.4-arch1-1
    Database driver: mysql
    Database version: 10.6.3-MariaDB-log
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0

**Comment by korlikiangel** [comment]
Same problem, after upgrading to 1.2.20. In 1.2.19 no problem at all.
I don't use Greenwing, 

Application version: 1.2.20
PHP version: 7.4.15
PHP SAPI: cgi-fcgi
HTTP Client: cURL
OS version: Linux 4.14.232-ovh-vps-grsec-zfs-classid
Database driver: postgres
Database version: 12.7 (Debian 12.7-1.pgdg100+1)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

I have installed plugins: 
Coverimage
Moon
metaMagik
Customizer
Group_assign
UpdateNotifier
Overwrite Translation
Sort_Board_By_Dates
KangarooJump
CustomUserCSS

**Comment by iulian-radu-at** [comment]
A solution which "works" independent of any plugin or base code is to comment all the code of the functions related to CSRF in BaseController. The downside is that the CSRF protection is completely turned off.

File:
```
https://github.com/kanboard/kanboard/blob/master/app/Controller/BaseController.php
```

Commented code:
```php
    protected function checkCSRFParam()
    {
//        if (! $this->token->validateCSRFToken($this->request->getStringParam('csrf_token'))) {
//            throw new AccessForbiddenException();
//        }
    }

    protected function checkReusableCSRFParam()
    {
//        if (! $this->token->validateReusableCSRFToken($this->request->getRawValue('csrf_token'))) {
//            throw new AccessForbiddenException();
//        }
    }

    protected function checkReusableGETCSRFParam()
    {
//        if (! $this->token->validateReusableCSRFToken($this->request->getStringParam('csrf_token'))) {
//            throw new AccessForbiddenException();
//        }
    }

    protected function checkCSRFForm()
    {
//        if (! $this->token->validateCSRFToken($this->request->getRawValue('csrf_token'))) {
//            throw new AccessForbiddenException();
//        }
    }
```

Another place where I needed to remove CSRF related code, so I can login, was in Http Request.

```
https://github.com/kanboard/kanboard/blob/master/app/Core/Http/Request.php
```

```php
    public function getValues()
    {
// before ->        if (! empty($this->post) && ! empty($this->post['csrf_token']) && $this->token->validateCSRFToken($this->post['csrf_token'])) {
        if (! empty($this->post) && ! empty($this->post['csrf_token'])) {
            unset($this->post['csrf_token']);
            return $this->filterValues($this->post);
        }

        return array();
    }
```

I hope this helps you.

**Comment by vmario89** [comment]
> Thank @iulian-radu-at . For my case, I just need to comment out this (leaving other three untouched, so I hope some level of CSRF protection is still working.
> 
> ```
> protected function checkReusableGETCSRFParam()
> {
> ```
> 
> // if (! $this->token->validateReusableCSRFToken($this->request->getStringParam('csrf_token'))) { // throw new AccessForbiddenException(); // } }
> 
> And the drag and drop works for me. I have no problem with login so I don't need to change the Request.php

i can confirm that only this one change fixes the problem for dragging a task from on column to another

**Comment by ghamed** [comment]
I can also confirm this problem still exist on fresh latest version without any plugins.

**Comment by Ahoja** [comment]
vmario89 - Many thanks. Problem still exists in latest upgrade. Commented out those 3 lines and using SSL without any changes to plugins. Cards/Tasks can be moved between columns now.

**Comment by Abraka** [comment]
Thx guys, comment out "protected function checkReusableGETCSRFParam()" help.
v. 1.2.21

**Comment by omego** [comment]
In addition to the above information, in my case it happens on filled boards with multiple columns and many cards.
Any new boards or boards with a 10-20 cards nothing happens.

```
Customizer
Calendar
Greenwing
Mailgun
SoundNotification
Gantt
Coverimage
UpdateNotifier
```

```
Application version: 1.2.20
PHP version: 7.3.19-1+ubuntu18.04.1+deb.sury.org+1
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 4.15.0-156-generic
Database driver: mysql
Database version: 8.0.27
```

**Comment by prema770** [comment]
Works well now thanks all for the tips. Generous and vibrant community. Hope we get the chance to contribute

**Comment by asifaziz01** [comment]
I was facing the same issue. The issue resolved as soon as I removed the plugin _Backlog [vistree + creecros | 1.0.3](https://github.com/vistree/kanboard-backlog)_

**Comment by PFranck06** [comment]
Version de l'application : master.unknown_revision
    Version de PHP : 8.0.18
    PHP SAPI : apache2handler
    Client HTTP : cURL
    Version du système d'exploitation : Linux 5.10.0-13-amd64
    Type de base de données : mysql
    Version de la base de donnée : 10.5.15-MariaDB-0+deb11u1
    Navigateur web : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0

Can someone help me please?
When my user has "Member of project" default permission: No problem
When i assign a new custom role: i can move tasks on the website but not from the API
:(

**Comment by stefanKP50** [comment]
Hi,
having same trouble, confirm all is ok after deleted backlog plugin (csrf not implemented in plugin)
could be same csrf problem with others plugins

**Comment by kwetnico** [comment]
Hi,

I have the same problem and I don't have the backlog plugin

**Comment by yaronelh** [comment]
Just in case anybody else is looking for the solution, it seems to do with mod_security, not a KB issue.

Source
https://kanboard.discourse.group/t/error-403-forbidden-when-creating-task-in-v1-2-18/1593

**Comment by grayed** [comment]
> Backlog

For the Backlog plugin, I've just published the fix: https://github.com/vistree/kanboard-backlog/pull/25 .

**Comment by jfbvm** [comment]
Backlog for me was the problem. Uninstalled it.

Running on Docker behind an Apache proxy.
